for _, plug in ipairs({
	"nvim-treesitter",
	"carbonfox",
	"cellular-automaton-nvim",
	"mini-misc",
	"mini-icons",
	"mini-starter",
	"mini-diff",
	"mini-extra",
	"mini-git",
	"mini-statusline",
	"mini-notify",
	"mini-sessions",
	"mini-jump",
	"mini-surround",
	"mini-pairs",
	"mini-pick",
	"mini-clue",
	"mini-files",
	"mini-visits",
	"render-markdown",
	"markdown-preview",
	"lsp",
	"lazydev",
	"conform-nvim",
	"neogit",
	"blink-cmp",
}) do
	require("josh.plugins." .. plug)
end
